defaults:
  - common
  - world_model
  - override generator: key_gen
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# === Dataset ===
dataset_path: None
dataset_name: "key_minigrid_dataset"

# === World Model Hyperparams ===
include_key: True

# === Frozen Parameters ===
encoder_path: None

# === World Model Eval ===
agent_path: None